config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get 'leagues', to: 'leagues#index'
  # get 'leagues/new', to: 'leagues#new'
  # get 'leagues/:id', to: 'leagues#show'
  resources :leagues do
    resources :user_leagues, only: :create
    resources :matches, only: %i[new create index]
    member do
      post "setmatches", to: "leagues#setmatches"
      delete "delete_player", to: "user_leagues#destroy"
    end
  end


  get "leagues/:id/invitation", to: "leagues#invitation", as: :invitation
  # post "leagues/:id/invitation", to: "user_leagues#create",

  resources :matches, only: [] do
    member do
      post "setwinner", to: "matches#setwinner"
    end
    collection do
      post "reload_round", to: "matches#reload_round"
    end
  end
end

app/models/league.rb
class League < ApplicationRecord
  has_many :user_leagues, dependent: :destroy
  has_many :users, through: :user_leagues
  has_many :matches, dependent: :destroy
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"

  validates :name, presence: true
  validates :sport, presence: true
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  skip_before_action :authenticate_user!, only: :invitation
  before_action :set_league, only: %i[show invitation join-league destroy set_points]
  def index
    @leagues = League.joins(:user_leagues).where("user_leagues.user_id = #{current_user.id}")
  end

  def new
    @league = League.new
  end

  def create
    @league = League.new(league_params)
    @league.creator = current_user
    if @league.save
      redirect_to league_path(@league)
    else
      render :new, status: :unprocessable_entity
    end
    UserLeague.create(league: @league, user: current_user, points: 0)
  end

  def show
    @league = League.find(params[:id])
    set_points
    @qr_code = RQRCode::QRCode.new(invitation_url(@league))
    @svg = @qr_code.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      standalone: true,
      module_size: 6
    )
    @leaderboard_players = User.joins(:user_leagues).where("user_leagues.league_id = #{@league.id}")
  end

  def destroy
    @league.destroy
    redirect_to leagues_path, status: :see_other
  end

  def invitation
    session[:previous_url] = request.fullpath
    @league = League.find(params[:id])
  end

  def setmatches
    @league = League.find(params[:id])
    @players = @league.users

    num_rounds = @players.size - 1
    num_matches = (1..@players.size).inject(:*) / (2 * (1..(@players.size - 2)).inject(:*))

    unless num_matches.fdiv(num_rounds) == num_matches.fdiv(num_rounds).round
      @max_round = num_rounds + 1
    else
      @max_round = num_rounds
    end

    round_num = 1
    @players.each do |player|
      adversaries = @players.where.not(id: player.id)
      adversaries.each do |adversary|
        if Match.where(league: @league).present?
          if Match.where(league: @league).last.round == round_num
            if round_num < @max_round
              round_num += 1
            else
              round_num = 1
            end
          end
        end
        if Match.where(player1: player, player2: adversary, league: @league).empty? && Match.where(player1: adversary, player2: player, league: @league).empty?
          while Match.where("matches.player1_id= #{player.id} OR matches.player2_id = #{player.id} OR matches.player1_id= #{adversary.id} OR matches.player2_id = #{adversary.id}").where(round: round_num, league: @league).present?
            if round_num < @max_round
              round_num += 1
            else
              round_num = 1
            end
          end
          match = Match.new(player1: player, player2: adversary, round: round_num)
          match.league = @league
          match.save
        end
      end
    end
    redirect_to league_matches_path(@league)
  end

  private

  def league_params
    params.require(:league).permit(:name, :sport)
  end

  def set_league
    @league = League.find(params[:id])
  end

  def set_points
    @players = @league.user_leagues
    @players.each do |player|
      @wins = @league.matches.where("winner_id = #{player.user_id}").count
      points = @wins * 3
      player.points = points
      player.save
    end
    @wins
  end
end

app/views/leagues/index.html.erb
<div class= "container page">
  <div class= "row index-league">
    <div class= "profile-infos">
      <div class="infos-index">
        <div class="personnal-infos-index">
          <h1>Hello <%= current_user.first_name %> !</h1>
          <h3 class="text-infos-index ms-4 me-4"> Here you can create your league and see all leagues you are in.</h3>
        </div>
        <div class="new-tournament" >
          <a class="btn btn-flat create-tournament mt-4 mb-4" href="/leagues/new">Create New League</a>
        </div>
      </div>
    </div>

  <div class="everything">
    <div class="your-leagues">
      <h2 class="mt-4 mb-4"> Your Leagues</h2>
     <% @leagues.order("created_at DESC").each do |league| %>

        <div class="position-relative">
          <%= link_to league_path(league), class: "text-decoration-none" do %>
            <div class="leagues">
              <div style="display: grid">

                <div class="mx-auto">
                  <p class="p-name-league"><%= league.name %></p>
                </div>
                <p class="creator-league">
                   Created by <strong><%= league.creator == current_user ? "you" : league.creator.first_name %></strong> <%= time_ago_in_words(league.created_at) %> ago

                </p>
                <div class="icon-tag d-flex justify-content-between">
                  <p class="sport-league">
                  <%= league.sport %></p>
                 <%= icon_tag(league) %>
                </div>

              </div>
            </div>
          <% end %>
          <div class="league-index-details position-absolute" style="top: 11px; right: 33px;">
            <% if league.creator == current_user %>
              <div class="d-flex flex-column mt-2">
                <%= link_to "X", league_path(league), class: "btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to cancel your league?" } %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/leagues/invitation.html.erb
<%# <%= link_to "Accept", accept_invitation_path(league, user_id: current_user.id), method: "POST" %>

<div class="container">
  <div class="module-wrapper text-center">
    <div class="module">
      <div class="container">
        <div class="invtions pagegit ">
          <h3 class= "mt-5", style="color:white">Hello!</h3>
          <p class="mb-3" style="color:white"><%= @league.creator.first_name %> <%= @league.creator.last_name %> has invited you to compete in '<%= @league.name %>' league where you will be playing <%= @league.sport %>.</p>
          <p>
          <button class="btn-accept">
          <%= link_to "Accept", league_user_leagues_path(@league), data: {turbo_method: :post} %>
          </button>
          <p>
          <%= link_to "Decline", "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley", target: :_blank, style: "text-decoration:none; color:white", class: "" %>
          </p>

        </div>
      </div>
    </div>
  </div>
  <div>
    <%= render "shared/newgame_animation" %>
  </div>
</div>

app/views/leagues/new.html.erb
<div class="container">
  <a href="/leagues"><i class="fa-solid fa-chevron-left"></i></a>
  <h1 class="text-center text-white mt-5"> Choose a name and a sport for your league.</h1>
  <h3 class="text-center text-white"> Share the link with your friends and have fun!</h3>

  <div class="sport-icons text-center mt-5 ms-5 me-5 d-flex justify-content-between">
    <div class="pingpong">
      <i class="fa-solid fa-table-tennis-paddle-ball fa-2xl"></i>
    </div>
    <div class="futbol">
      <i class="fa-solid fa-futbol fa-2xl "></i>
    </div>
    <div class="bowling">
      <i class="fa-solid fa-bowling-ball fa-2xl"></i>
    </div>
    <div class="micro">
      <i class="fa-solid fa-microphone-lines fa-2xl"></i>
    </div>
  </div>

  <div class="form-league">
    <div class="form-inputs form_info">
      <div class="form-actions">
        <%= simple_form_for @league do |f| %>
          <%= f.input :name %>
          <%= f.input :sport, :collection => ["Arm Wrestling", "Beer Pong", "Billiard", "Boxing", "Coding", "Darts", "Foosball", "Karaoke",  "Marbles", "Ping Pong", "Tennis", "Weightlifting", "Bowling", "Other"] %>
          <div class="form-actions text-center">
            <%= f.button :submit, "Create", class: "btn btn-primary mt-5" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/leagues/show.html.erb
<%= render "shared/league_info" %>

<div class="league-slider mt-3 mb-4">
  <%= link_to league_path(@league), class: "l-slider-leaderboard text-decoration-none" do %>
    <i class="fa-solid fa-table-list"></i>
  <% end %>
  <% if @league.matches.present? %>
    <%= link_to league_matches_path(@league), class: "l-slider-matches", id: "defunc-slider" do %>
      <i class="fa-solid fa-user-group"></i>
    <% end %>
  <% else %>
    <span class="l-slider-matches text-black"><i class="fa-solid fa-user-group"></i></span>
  <% end %>
</div>


<div class="conditional-league-items">
  <% if @league.users.size <3 %>
    <p style="color:white; background-color:#E60F05; text-align:center; font-size:14px; width:250px; margin:auto; border-radius:5px;"><i class="fa-solid fa-triangle-exclamation"></i> Your league needs three or more players before you can start<i class="fa-solid fa-triangle-exclamation"></i></p>
  <% end %>

  <% if @league.users.size >2 && @league.creator != current_user && @league.matches.empty? %>
    <p style="color:white; background-color:#E60F05; text-align:center; font-size:14px; width:300px; margin:auto; border-radius:5px;"><i class="fa-solid fa-triangle-exclamation"></i> Wait for <%= @league.creator.first_name %> to start the league<i class="fa-solid fa-triangle-exclamation"></i></p>
  <% end %>

  <% if @league.creator == current_user && @league.matches.empty? && @league.users.size >2%>
    <div class="btn-set-matches">
      <%= link_to "Start League!", league_matches_path(@league), data: { turbo_method: :post } %>
    </div>
  <% end %>
</div>

<div class="table-container" style="margin-top:15px;">
  <table class="table table-striped table-hover" style="background-color:#ffffff; border-radius:10px; overflow: hidden">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col"></th>
        <th style='text-align:center' scope="col">Players</th>
        <th scope="col">Played</th>
        <th scope="col">Won</th>
        <th scope="col">Points</th>
      </tr>
    </thead>
    <tbody>
      <% i = 1 %>
      <% @leaderboard_players.order("points DESC").each do |player| %>
        <tr>
        <th style='text-align:center' scope="row"><%= i %></th>
        <td>
          <% if (@league.creator == current_user || current_user == player) && @league.matches.empty? %>
            <div class="d-flex flex-column">
              <%= link_to "X", delete_player_league_path(@league, player_id: player.id), class: "btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove this player from your league?" } %>
            </div>
          <% end %>
        </td>
        <td style='text-align:center'><%= player.first_name %> <%= player.last_name %>
        </td>
        <% u_l = @league.user_leagues.where("user_id = #{player.id}").first %>
        <% u_m = @league.matches.where("(player1_id = #{player.id} OR player2_id = #{player.id}) AND winner_id IS NOT NULL") %>
        <td style='text-align:center'><%= u_m.count %></td>
        <td style='text-align:center'><%= u_l.points / 3 %></td>
        <td style='text-align:center'><%= u_l.points %>
        </td>
        </tr>
      <% i += 1 %>
    <% end %>
    </tbody>
  </table>
</div>