config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get 'leagues', to: 'leagues#index'
  # get 'leagues/new', to: 'leagues#new'
  # get 'leagues/:id', to: 'leagues#show'
  resources :leagues do
    resources :user_leagues, only: :create
    resources :matches, only: %i[new create index]
    member do
      post "setmatches", to: "leagues#setmatches"
      delete "delete_player", to: "user_leagues#destroy"
    end
  end


  get "leagues/:id/invitation", to: "leagues#invitation", as: :invitation
  # post "leagues/:id/invitation", to: "user_leagues#create",

  resources :matches, only: [] do
    member do
      post "setwinner", to: "matches#setwinner"
    end
    collection do
      post "reload_round", to: "matches#reload_round"
    end
  end
end

app/views/shared/_avatar.html.erb
<img class="avatar-index" alt="avatar" src="https://inspireddentalcare.co.uk/wp-content/uploads/2016/05/Facebook-default-no-profile-pic.jpg" />

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
 <div class="footer-copyright">
    © 2022 Le Wapong
  </div>

  <div class="footer-links">
    <a href="https://github.com/manuelkneib/Le_WaPong" target="_blank"><i class="fab fa-github" ></i></a>
    <a href="https://www.instagram.com/lewagonportugal/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/pages/Le-Wagon/378229659642717" target="_blank"><i class="fab fa-facebook"></i></a>
  </div>

</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_league_info.html.erb
<a href="/leagues"><i class="fa-solid fa-chevron-left m-3"></i></a>



<h2 class="text-center">Players table and details
</h2>
  <div class="container league-container" style="margin-top: 20px">
    <div class="module-invite d-flex flex-column align-items-center ms-4 me-4 "><div class="module-wrapper ">
      <div class="module accordion accordion-league" id="accordionExample">
        <div class="container accordion-item accordion-league-item">

           <div class="accordion-header accordion-league-header" id="headingOne">
            <button class="accordion-button league-accordion-button fifi <%= "collapsed" if @league.matches.present? %>" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne" id="fifi">
              <%= @league.name %>
            </button>
          </div>


          <div id="collapseOne" class="accordion-collapse collapse <%= "show" if !@league.matches.present? %>" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <h3 class="text-center mb-3" style="font-size:20px;"> Competing in:
                <div class="sport-info mt-3 mb-3 p-2 d-flex flex-column align-items-center" >
                <strong><%= @league.sport %></strong>
                <%= icon_tag(@league) %>
                </div>
              </h3>
              <h3 class="text-center" style="font-size:18px;"> Organized by:
                <strong><%= @league.creator.first_name %> <%= @league.creator.last_name %></strong>
              </h3>

              <% if @league.matches.empty? && @league.creator == current_user %>
                <div class="conditional-invites mt-4">
                  <div class="input-group" data-controller="clipboard" data-clipboard-feedback-text-value="Copied!" style="justify-content: center;">
                    <input type="hidden" class="form-control" data-clipboard-target="input" type="text" value="<%= invitation_url %>" readonly>
                    <button id="copy-button" class="btn btn-outline-primary" style="width:220px; color:grey;" data-action="click->clipboard#copy">Copy the invitation link</button>
                  </div>
                </div>
                <div class="qr-code-div" style="margin-top: 25px;">
                  <p style="color: white; text-align: center; margin-bottom: 3px;">Scan to join the tournament!</p>
                  <div class="QR-code-invitation">
                    <%= @svg.html_safe %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon position-relative">
  <div class="navbar-logo">
    <a class="navbar-brand" href="/leagues">
      <%= image_tag "logo_icon_bold_complete.png", class: 'logo_image' %>
    </a>
  </div>
  <div class="hamburger-navbar">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  </div>
  <div class="collapse navbar-collapse dropdown-options" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "My Leagues", leagues_path, class: "nav-link p-0" %>
          <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_newgame_animation.html.erb
<div class="animation_invite">
  <div id="loading">
    <div id="ball"></div>
    <div id="string"></div>
    <div id="paddle">
      <div id="head"></div>
      <div id="handle"></div>
    </div>
  </div>
</div>