config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get 'leagues', to: 'leagues#index'
  # get 'leagues/new', to: 'leagues#new'
  # get 'leagues/:id', to: 'leagues#show'
  resources :leagues do
    resources :user_leagues, only: :create
    resources :matches, only: %i[new create index]
    member do
      post "setmatches", to: "leagues#setmatches"
      delete "delete_player", to: "user_leagues#destroy"
    end
  end


  get "leagues/:id/invitation", to: "leagues#invitation", as: :invitation
  # post "leagues/:id/invitation", to: "user_leagues#create",

  resources :matches, only: [] do
    member do
      post "setwinner", to: "matches#setwinner"
    end
    collection do
      post "reload_round", to: "matches#reload_round"
    end
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :league
  belongs_to :player1, class_name: "User", foreign_key: "player1_id"
  belongs_to :player2, class_name: "User", foreign_key: "player2_id"
  belongs_to :winner, class_name: "User", foreign_key: "winner_id", optional: true

  has_many :user_matches, dependent: :destroy
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @league = League.find(params[:league_id])
    @players = @league.users
    set_league_matches if Match.where(league: @league).empty?
    @matches = Match.where(league: @league).order("matches.id ASC")
    @max_round = @matches.maximum(:round)
  end

  def new
    @match = Match.new
  end

  def create
    @league = League.find(params[:league_id])
    @players = @league.users


    redirect_to league_matches_path(@league)
  end

  def setwinner
    match = Match.find(params[:id])
    match.winner = User.find(params[:winner_id])
    match.save

    # redirect_to league_matches_path(match.league)
  end

  def reload_round
    @matches = Match.where(id: params[:matches])
    @matches.each do |match|
      match.winner = nil
      match.save
    end
    match = @matches.first
    redirect_to league_matches_path(match.league)
  end

  private

  def match_params
    params.require(:match).permit(:league_id)
  end

  def set_league_matches
    num_rounds = @players.size - 1
    num_matches = (1..@players.size).inject(:*) / (2 * (1..(@players.size - 2)).inject(:*))

    unless num_matches.fdiv(num_rounds) == num_matches.fdiv(num_rounds).round
      @max_round = num_rounds + 1
    else
      @max_round = num_rounds
    end

    round_num = 1
    @players.each do |player|
      adversaries = @players.where.not(id: player.id)
      adversaries.each do |adversary|
        if Match.where(league: @league).present?
          if Match.where(league: @league).last.round == round_num
            if round_num < @max_round
              round_num += 1
            else
              round_num = 1
            end
          end
        end
        if Match.where(player1: player, player2: adversary, league: @league).empty? && Match.where(player1: adversary, player2: player, league: @league).empty?
          while Match.where("matches.player1_id= #{player.id} OR matches.player2_id = #{player.id} OR matches.player1_id= #{adversary.id} OR matches.player2_id = #{adversary.id}").where(round: round_num, league: @league).present?
            if round_num < @max_round
              round_num += 1
            else
              round_num = 1
            end
          end

          match = Match.new(player1: player, player2: adversary, round: round_num)
          match.league = @league
          match.save
        end
      end
    end
  end
end

app/views/matches/_reload_round.html.erb
<% if @league.creator == current_user %>
  <div class="reload">
    <div class="reload-icon">
      <%# <i><%= link_to fa_icon "fa-solid fa-rotate-right", leagues_path %>
      <%= link_to reload_round_matches_path(matches: @matches.where(round: round).ids), data: { turbo_method: :post }, style:"text-decoration:none" do %>
        <i class="fa-solid fa-rotate-right"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/matches/index.html.erb
<%= render "shared/league_info" %>

<div class="match-slider mt-3 mb-4">
  <%= link_to league_path(@league), class: "m-slider-leaderboard text-decoration-none" do %>
    <i class="fa-solid fa-table-list"></i>
  <% end %>
  <%= link_to league_matches_path(@league), class: "m-slider-matches" do%>
    <i class="fa-solid fa-user-group"></i>
  <% end %>
</div>

<div class="w-100">
  <% @max_round.times do |round| %>
  <div class="overall-matches">
      <% round += 1 %>
      <div class="accordion accordion-flush" id="accordionFlushExample">
        <div class="round accordion-item" style="border-radius: 5px">
          <div class="round-num">
            <h2 class="lead accordion-header" id="flush-heading<%= round %>">
              <button class="accordion-button collapsed" id="accordion-btn" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse<%= round %>" aria-expanded="true" aria-controls="flush-collapse<%= round %>">
                <strong>ROUND <%= round %></strong>
              </button>
            </h2>
          </div>
          <% @matches.where(round: round).each do |match| %>
          <div id="flush-collapse<%= round %>" class="accordion-collapse collapse" aria-labelledby="flush-heading<%= round %>" data-bs-parent="#accordionFlushExample">
              <div class="match d-flex justify-content-between align-items-center position-relative accordion-body" data-controller="input-round">
                <div>
                  <%= link_to setwinner_match_path(match, winner_id: match.player1), data: { turbo_method: :post }, style:"text-decoration:none" do %>
                    <div class="player1 <%= "btn btn-success match-winner" if match.player1 == match.winner %>" data-action="click->input-round#send" data-input-round-target="player1">
                      <%= "#{match.player1.first_name} #{match.player1.last_name}" %>
                    </div>
                  <% end %>
                </div>
                <div class="vs">vs</div>
                <div>
                  <%= link_to setwinner_match_path(match, winner_id: match.player2), data: { turbo_method: :post }, style:"text-decoration:none" do %>
                    <div class="player2 <%= "btn btn-success match-winner" if match.player2 == match.winner %>" data-action="click->input-round#send" data-input-round-target="player2">
                      <%= "#{match.player2.first_name} #{match.player2.last_name}" %>
                    </div>
                  <% end %>
                </div>
              </div>
          </div>
          <% end %>
        </div>
      </div>
  </div>
    <% end %>
</div>